### ISSUE TITLE
Could you please suggest any book to learn Axon ?

### ISSUE THREAD

**Issue by ghost** [AxonIQ/giftcard-demo#7]
Could you please suggest any book to learn Axon ?

**Comment by smcvb** [comment]
Firstly, sorry for the extreme late reply here, @ghost.
I guess you've already found a different way to learn more about Axon.
At the time of your comment, the answer would've been "there aren't any, except for the [Reference Guide](https://docs.axoniq.io/reference-guide/)."

Nowadays though, there's a lot more material out there to learn and understand Axon a lot better.
A book you could have a look at (granted that you're still interested), is [Practical Domain-Driven Design in Enterprise Java: Using Jakarta EE, Eclipse MicroProfile, Spring Boot, and the Axon Framework](https://www.amazon.com/Practical-Domain-Driven-Design-Enterprise-Java/dp/1484245423).

Next to this, AxonIQ provides dedicated training, as well as a completely [online course set](https://academy.axoniq.io/), so that you get input on Framework and Server in a clear-cut fashion.
If you need any other information, AxonIQ's [learn section](https://axoniq.io/resources/architectural-concepts) might provide some additional information.
Lastly, you can always drop questions on AxonIQ's dedicated [forum](https://discuss.axoniq.io/).

Again, apologies for the late reply.
May the above serve others that might end up on this issue nonetheless.
